// <auto-generated />
using System;
using EscapeRoom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscapeRoom.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscapeRoom.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscapeRoomId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfParticipants")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingDateTime")
                        .HasDatabaseName("idx_bookings_datetime");

                    b.HasIndex("EscapeRoomId")
                        .HasDatabaseName("idx_bookings_room_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_bookings_player_id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevels");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.EscapeRoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId")
                        .HasDatabaseName("idx_rooms_difficulty_id");

                    b.ToTable("EscapeRooms");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.Hint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EscapeRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscapeRoomId");

                    b.ToTable("Hints");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_players_email");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.Booking", b =>
                {
                    b.HasOne("EscapeRoom.Core.Entities.EscapeRoomEntity", "EscapeRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("EscapeRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeRoom.Core.Entities.Player", "Player")
                        .WithMany("Bookings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscapeRoom");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.EscapeRoomEntity", b =>
                {
                    b.HasOne("EscapeRoom.Core.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("EscapeRooms")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.Hint", b =>
                {
                    b.HasOne("EscapeRoom.Core.Entities.EscapeRoomEntity", "EscapeRoom")
                        .WithMany("Hints")
                        .HasForeignKey("EscapeRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscapeRoom");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.DifficultyLevel", b =>
                {
                    b.Navigation("EscapeRooms");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.EscapeRoomEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Hints");
                });

            modelBuilder.Entity("EscapeRoom.Core.Entities.Player", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
